/**
 * @author Peter Fortin
 */

import java.io.Serializable;

public class University implements Serializable {

	/* Data Fields */
	
	private static final long serialVersionUID = -3766387064468777156L; //This was auto generated by Eclipse for Serializable
	private String uniName;
	private String address;
	private String city;
	private String state;
	private String zipCode;
	private String phoneNumber;
	private double inStateUnder12;
	private double inStateUnder18;
	private double inState18AndOver;
	private double outStateUnder12;
	private double outStateUnder18;
	private double outState18AndOver;
	private double mealPlanA;
	private double mealPlanB;
	private double mealPlanC;
	private double healthCareUnder11;
	private double healthCareUnder16;
	private double healthCare18AndOver;
	private double lateFeeRate;
	private double incidentalFeeRate;
	private double incidentalFeeMax;
	
	
	/* Constructors */
	
	public University(String uniName, String address, String city, String state, String zipCode, String phoneNumber,
			double inStateUnder12, double inStateUnder18, double inState18AndOver, double outStateUnder12,
			double outStateUnder18, double outState18AndOver, double mealPlanA, double mealPlanB, double mealPlanC,
			double healthCareUnder11, double healthCareUnder16, double healthCare18AndOver, double lateFeeRate,
			double incidentalFeeRate, double incidentalFeeMax) {
		
		this.uniName = uniName;
		this.address = address;
		this.city = city;
		this.state = state;
		this.zipCode = zipCode;
		this.phoneNumber = phoneNumber;
		this.inStateUnder12 = inStateUnder12;
		this.inStateUnder18 = inStateUnder18;
		this.inState18AndOver = inState18AndOver;
		this.outStateUnder12 = outStateUnder12;
		this.outStateUnder18 = outStateUnder18;
		this.outState18AndOver = outState18AndOver;
		this.mealPlanA = mealPlanA;
		this.mealPlanB = mealPlanB;
		this.mealPlanC = mealPlanC;
		this.healthCareUnder11 = healthCareUnder11;
		this.healthCareUnder16 = healthCareUnder16;
		this.healthCare18AndOver = healthCare18AndOver;
		this.lateFeeRate = lateFeeRate;
		this.incidentalFeeRate = incidentalFeeRate;
		this.incidentalFeeMax = incidentalFeeMax; 
	}


	/* Getters and Setters */
	
	public String getUniName() {
		return this.uniName;
	}


	public void setUniName(String uniName) {
		this.uniName = uniName;
	}


	public String getAddress() {
		return this.address;
	}


	public void setAddress(String address) {
		this.address = address;
	}


	public String getCity() {
		return this.city;
	}


	public void setCity(String city) {
		this.city = city;
	}


	public String getState() {
		return this.state;
	}


	public void setState(String state) {
		this.state = state;
	}


	public String getZipCode() {
		return this.zipCode;
	}


	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}


	public String getPhoneNumber() {
		return this.phoneNumber;
	}


	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}


	public double getInStateUnder12() {
		return this.inStateUnder12;
	}


	public void setInStateUnder12(double inStateUnder12) {
		this.inStateUnder12 = inStateUnder12;
	}


	public double getInStateUnder18() {
		return this.inStateUnder18;
	}


	public void setInStateUnder18(double inStateUnder18) {
		this.inStateUnder18 = inStateUnder18;
	}


	public double getInState18AndOver() {
		return this.inState18AndOver;
	}


	public void setInState18AndOver(double inState18AndOver) {
		this.inState18AndOver = inState18AndOver;
	}


	public double getOutStateUnder12() {
		return this.outStateUnder12;
	}


	public void setOutStateUnder12(double outStateUnder12) {
		this.outStateUnder12 = outStateUnder12;
	}


	public double getOutStateUnder18() {
		return this.outStateUnder18;
	}


	public void setOutStateUnder18(double outStateUnder18) {
		this.outStateUnder18 = outStateUnder18;
	}


	public double getOutState18AndOver() {
		return this.outState18AndOver;
	}


	public void setOutState18AndOver(double outState18AndOver) {
		this.outState18AndOver = outState18AndOver;
	}


	public double getMealPlanA() {
		return this.mealPlanA;
	}


	public void setMealPlanA(double mealPlanA) {
		this.mealPlanA = mealPlanA;
	}


	public double getMealPlanB() {
		return this.mealPlanB;
	}


	public void setMealPlanB(double mealPlanB) {
		this.mealPlanB = mealPlanB;
	}


	public double getMealPlanC() {
		return this.mealPlanC;
	}


	public void setMealPlanC(double mealPlanC) {
		this.mealPlanC = mealPlanC;
	}


	public double getHealthCareUnder11() {
		return this.healthCareUnder11;
	}


	public void setHealthCareUnder11(double healthCareUnder11) {
		this.healthCareUnder11 = healthCareUnder11;
	}


	public double getHealthCareUnder16() {
		return this.healthCareUnder16;
	}


	public void setHealthCareUnder16(double healthCareUnder16) {
		this.healthCareUnder16 = healthCareUnder16;
	}


	public double getHealthCare18AndOver() {
		return this.healthCare18AndOver;
	}


	public void setHealthCare18AndOver(double healthCare18AndOver) {
		this.healthCare18AndOver = healthCare18AndOver;
	}


	public double getLateFeeRate() {
		return this.lateFeeRate;
	}


	public void setLateFeeRate(double lateFeeRate) {
		this.lateFeeRate = lateFeeRate;
	}


	public double getIncidentalFeeRate() {
		return this.incidentalFeeRate;
	}


	public void setIncidentalFeeRate(double incidentalFeeRate) {
		this.incidentalFeeRate = incidentalFeeRate;
	}


	public double getIncidentalFeeMax() {
		return this.incidentalFeeMax;
	}


	public void setIncidentalFeeMax(double incidentalFeeMax) {
		this.incidentalFeeMax = incidentalFeeMax;
	}

	
	/* Utility Methods */
	
	public boolean equals(University uni) {
		return this.uniName.equals(uni.uniName);
	}
	
	public int compareTo(University uni) {
		return this.uniName.compareTo(uni.uniName);
	}
	
	public String toString() {
		return this.uniName + " "
			 + this.address + " "
			 + this.city + " "
			 + this.state + " "
			 + this.zipCode + " "
			 + this.phoneNumber + " "
			 + this.inStateUnder12 + " "
			 + this.inStateUnder18 + " "
			 + this.inState18AndOver + " "
			 + this.outStateUnder12 + " "
			 + this.outStateUnder18 + " "
			 + this.outState18AndOver + " "
			 + this.mealPlanA + " "
			 + this.mealPlanB + " "
			 + this.mealPlanC + " "
			 + this.healthCareUnder11 + " "
			 + this.healthCareUnder16 + " "
			 + this.healthCare18AndOver + " "
			 + this.lateFeeRate + " "
			 + this.incidentalFeeRate + " "
			 + this.incidentalFeeMax; 
	}
}
